### ISSUE TITLE
Networks analysis doesn't distinguish between progressive and concurrent enrollment

### ISSUE THREAD

**Issue by dannycab** [PERLMSU/ProjectPathways#1]
In the notebook `07-19-phy_courses.ipynb`, the order of courses in the list determines, which course follows which. However, the only variable used is the list `crse_code`. Thus, concurrent enrollment is not taken into account, which requires looking at the `crse_code` and `term_code` simultaneously.

**Comment by mnky9800n** [comment]
do you mean, it appears that every course is taken separately in time, as opposed to some courses are taken at the same time?

**Comment by dannycab** [comment]
Sort of. It means that a connection between two courses could be because one is taken before the other or because they are taken at the same time.
