### ISSUE TITLE
Network analysis doesn't handle re-enrollment in the same course

### ISSUE THREAD

**Issue by dannycab** [PERLMSU/ProjectPathways#2]
In the notebook `07-27_req_phy_crse_networkx.ipynb`, courses where students re-enrolled in the same course are not represented in the network diagrams (i.e., self-loops).

**Comment by mnky9800n** [comment]
you mean, if they drop, and re-enroll in a different semester?

**Comment by dannycab** [comment]
Yes, that's correct.
